# Антонов Павел - Вторая лаба по NumPy

### Импортировать NumPy под именем np

In [84]:
import numpy as np

### Перемножить матрицы 5x3 и 3x2

In [85]:
first_matrix = np.arange(15).reshape((5, 3))
second_matrix = np.arange(6).reshape((3, 2))
np.dot(first_matrix, second_matrix)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

### Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [86]:
vec = np.arange(10)
vec[(vec >= 3) & (vec <= 8)] *= -1
vec

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

### Создать 5x5 матрицу со значениями в строках от 0 до 4

In [87]:
vec = np.arange(5)
np.tile(vec, (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### Есть генератор, сделать с его помощью массив

In [88]:
iterable = (x*x for x in range(5))
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

### Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [89]:
np.linspace(0, 1, 12)[1:11]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

### Отсортировать вектор

In [90]:
vec = np.random.random((1,5))[0]
vec.sort()
vec

array([0.20026157, 0.2052672 , 0.30398673, 0.52324143, 0.70933556])

### Проверить, одинаковы ли 2 numpy массива

In [91]:
np.array_equal(np.arange(5), np.arange(5))

True

### Сделать массив неизменяемым

In [92]:
vec = np.arange(5)
vec.flags.writeable = False

### Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [93]:
vec = np.random.random((10, 2))
x, y = vec[:,0], vec[:,1]
np.array([np.sqrt(x**2 + y**2), np.arctan2(y, x)])

array([[0.57162138, 0.84084543, 0.56134705, 0.71117773, 0.2554298 ,
        0.30513824, 0.55980507, 0.53975727, 0.99905489, 0.43109204],
       [0.06821379, 0.20741371, 1.11440676, 1.5626668 , 0.55917229,
        1.02483197, 0.04104247, 0.55802466, 0.51351751, 1.39099737]])

### Заменить максимальный элемент на ноль

In [94]:
vec = np.arange(5)
vec[vec.argmax()] = 0
vec

array([0, 1, 2, 3, 0])

### Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [95]:
x, y = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
result = np.column_stack((x.ravel(), y.ravel()))
result.reshape(1, 50).reshape(5, 5, 2)

array([[[0.  , 0.  ],
        [0.25, 0.  ],
        [0.5 , 0.  ],
        [0.75, 0.  ],
        [1.  , 0.  ]],

       [[0.  , 0.25],
        [0.25, 0.25],
        [0.5 , 0.25],
        [0.75, 0.25],
        [1.  , 0.25]],

       [[0.  , 0.5 ],
        [0.25, 0.5 ],
        [0.5 , 0.5 ],
        [0.75, 0.5 ],
        [1.  , 0.5 ]],

       [[0.  , 0.75],
        [0.25, 0.75],
        [0.5 , 0.75],
        [0.75, 0.75],
        [1.  , 0.75]],

       [[0.  , 1.  ],
        [0.25, 1.  ],
        [0.5 , 1.  ],
        [0.75, 1.  ],
        [1.  , 1.  ]]])

### Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [96]:
x, y = np.meshgrid(np.linspace(2, 3, 5), np.linspace(0, 1, 5), indexing="xy")
result = 1 / (x - y)
result

array([[0.5       , 0.44444444, 0.4       , 0.36363636, 0.33333333],
       [0.57142857, 0.5       , 0.44444444, 0.4       , 0.36363636],
       [0.66666667, 0.57142857, 0.5       , 0.44444444, 0.4       ],
       [0.8       , 0.66666667, 0.57142857, 0.5       , 0.44444444],
       [1.        , 0.8       , 0.66666667, 0.57142857, 0.5       ]])

### Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [97]:
np_ints = [np.uint, np.uint0, np.uint16, np.uint32, np.uint64, np.uint8, np.uintc, np.uintp, np.int, np.int0, np.int16, np.int32, np.int64, np.int8, np.intc, np.integer, np.intp]
np_floats = [np.float, np.float16, np.float32, np.float64]

for type_int in np_ints:
    type_info = np.iinfo(type_int)
    print("Название", type_int, "MIN:", type_info.min, "MAX:", type_info.max)

for type_float in np_floats:
    type_info = np.finfo(type_float)
    print("Название", type_float, "MIN:", type_info.min, "MAX:", type_info.eps)

Название <class 'numpy.uint32'> MIN: 0 MAX: 4294967295
Название <class 'numpy.uint64'> MIN: 0 MAX: 18446744073709551615
Название <class 'numpy.uint16'> MIN: 0 MAX: 65535
Название <class 'numpy.uint32'> MIN: 0 MAX: 4294967295
Название <class 'numpy.uint64'> MIN: 0 MAX: 18446744073709551615
Название <class 'numpy.uint8'> MIN: 0 MAX: 255
Название <class 'numpy.uintc'> MIN: 0 MAX: 4294967295
Название <class 'numpy.uint64'> MIN: 0 MAX: 18446744073709551615
Название <class 'int'> MIN: -2147483648 MAX: 2147483647
Название <class 'numpy.int64'> MIN: -9223372036854775808 MAX: 9223372036854775807
Название <class 'numpy.int16'> MIN: -32768 MAX: 32767
Название <class 'numpy.int32'> MIN: -2147483648 MAX: 2147483647
Название <class 'numpy.int64'> MIN: -9223372036854775808 MAX: 9223372036854775807
Название <class 'numpy.int8'> MIN: -128 MAX: 127
Название <class 'numpy.intc'> MIN: -2147483648 MAX: 2147483647
Название <class 'numpy.integer'> MIN: -2147483648 MAX: 2147483647
Название <class 'numpy.int64

### Напечатать все значения в массиве

In [98]:
vec = np.arange(5)
for tmp in vec:
    print(tmp)

0
1
2
3
4


### Найти ближайшее к заданному значению число в заданном массиве

In [99]:
tmp = 5.6
vec = np.arange(10)
vec[(np.abs(vec - tmp)).argmin()]

6

### Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)

In [100]:
x, y = np.meshgrid(np.linspace(0, 1, 3), np.linspace(0, 1, 3), indexing="xy")
x_y_array = np.column_stack((x.ravel(), y.ravel()))
new_x_y_array = []
for i in x_y_array:
    new_x_y_array.append(tuple(i))
    new_x_y_array.append(tuple(i))
    new_x_y_array.append(tuple(i))

r, g, b = np.meshgrid(np.linspace(0, 255, 3), np.linspace(0, 255, 3), np.linspace(0, 255, 3))
r_g_b_array = np.column_stack((r.ravel(), g.ravel(), b.ravel()))
new_color = []
for i in r_g_b_array:
    new_color.append(tuple(i))

result = []
for i in range(len(new_x_y_array)):
    result.append((new_x_y_array[i], new_color[i]))

result

[((0.0, 0.0), (0.0, 0.0, 0.0)),
 ((0.0, 0.0), (0.0, 0.0, 127.5)),
 ((0.0, 0.0), (0.0, 0.0, 255.0)),
 ((0.5, 0.0), (127.5, 0.0, 0.0)),
 ((0.5, 0.0), (127.5, 0.0, 127.5)),
 ((0.5, 0.0), (127.5, 0.0, 255.0)),
 ((1.0, 0.0), (255.0, 0.0, 0.0)),
 ((1.0, 0.0), (255.0, 0.0, 127.5)),
 ((1.0, 0.0), (255.0, 0.0, 255.0)),
 ((0.0, 0.5), (0.0, 127.5, 0.0)),
 ((0.0, 0.5), (0.0, 127.5, 127.5)),
 ((0.0, 0.5), (0.0, 127.5, 255.0)),
 ((0.5, 0.5), (127.5, 127.5, 0.0)),
 ((0.5, 0.5), (127.5, 127.5, 127.5)),
 ((0.5, 0.5), (127.5, 127.5, 255.0)),
 ((1.0, 0.5), (255.0, 127.5, 0.0)),
 ((1.0, 0.5), (255.0, 127.5, 127.5)),
 ((1.0, 0.5), (255.0, 127.5, 255.0)),
 ((0.0, 1.0), (0.0, 255.0, 0.0)),
 ((0.0, 1.0), (0.0, 255.0, 127.5)),
 ((0.0, 1.0), (0.0, 255.0, 255.0)),
 ((0.5, 1.0), (127.5, 255.0, 0.0)),
 ((0.5, 1.0), (127.5, 255.0, 127.5)),
 ((0.5, 1.0), (127.5, 255.0, 255.0)),
 ((1.0, 1.0), (255.0, 255.0, 0.0)),
 ((1.0, 1.0), (255.0, 255.0, 127.5)),
 ((1.0, 1.0), (255.0, 255.0, 255.0))]

### Дан массив (100,2) координат, найти расстояние от каждой точки до каждой

In [101]:
coordinates = np.random.random((100, 2))
result = np.zeros((100, 100))
for i in range(100):
    for j in range(100):
        result[i][j] = np.linalg.norm(np.abs(coordinates[i] - coordinates[j]))
result

array([[0.        , 0.66655724, 0.60425187, ..., 0.34352604, 0.48520325,
        0.20331632],
       [0.66655724, 0.        , 0.26525676, ..., 0.32339063, 0.32452158,
        0.6809359 ],
       [0.60425187, 0.26525676, 0.        , ..., 0.31172561, 0.47963453,
        0.6968593 ],
       ...,
       [0.34352604, 0.32339063, 0.31172561, ..., 0.        , 0.24986061,
        0.39047285],
       [0.48520325, 0.32452158, 0.47963453, ..., 0.24986061, 0.        ,
        0.41490492],
       [0.20331632, 0.6809359 , 0.6968593 , ..., 0.39047285, 0.41490492,
        0.        ]])

### Преобразовать массив из float в int

In [102]:
np.random.random(10).astype(np.int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Дан файл: Как прочитать его?

In [103]:
#np.genfromtxt('./file.txt', delimiter = ',')

### Каков эквивалент функции enumerate для numpy массивов?

In [104]:
#np.ndenumerate

### Сформировать 2D массив с распределением Гаусса

In [105]:
np.random.normal(size=(5, 5))

array([[ 1.18307563, -0.4538487 ,  0.0157256 , -0.51701216, -0.38387257],
       [ 2.22564319,  1.7004324 ,  0.33019354,  0.20362456,  0.0342908 ],
       [ 0.71772918, -0.42550352, -0.39437332,  0.95949787, -0.32840276],
       [ 0.80713843,  1.20914889, -1.50204587, -1.2399746 ,  0.39631987],
       [ 0.35526131,  0.76113596, -1.80797518,  0.6053287 ,  0.3502076 ]])

### Случайно расположить p элементов в 2D массив

In [106]:
result = np.zeros((5,5))
np.put(result, np.random.choice(range(25), 10, replace=False), -1)
result

array([[ 0.,  0., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [-1.,  0., -1., -1.,  0.],
       [ 0.,  0., -1.,  0.,  0.],
       [-1., -1., -1., -1., -1.]])

### Отнять среднее из каждой строки в матрице

In [107]:
result = np.arange(49).reshape(7, 7)
result = result - result.mean(axis=1)
result

array([[ -3.,  -9., -15., -21., -27., -33., -39.],
       [  4.,  -2.,  -8., -14., -20., -26., -32.],
       [ 11.,   5.,  -1.,  -7., -13., -19., -25.],
       [ 18.,  12.,   6.,   0.,  -6., -12., -18.],
       [ 25.,  19.,  13.,   7.,   1.,  -5., -11.],
       [ 32.,  26.,  20.,  14.,   8.,   2.,  -4.],
       [ 39.,  33.,  27.,  21.,  15.,   9.,   3.]])

### Отсортировать матрицу по n-ому столбцу

In [108]:
result = np.arange(49).reshape(7, 7)[::-1]
result[result[:,2].argsort()]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

### Определить, есть ли в 2D массиве нулевые столбцы

In [109]:
#np.all((result == 0), axis=1)

### Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [110]:
a = np.ones(10)
b = np.arange(10)
for i in b:
    a[i] += 1
a

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

### Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [111]:
#np.unique(array, axis=0)

### Дан четырехмерный массив, посчитать сумму по последним двум осям

In [112]:
array = np.random.randint(0,10, (6,6,6,6))
result = array.reshape(array.shape[:-2] + (-1,)).sum(axis=-1)
result

array([[127, 145, 152, 165, 161, 183],
       [168, 161, 152, 165, 135, 142],
       [150, 171, 153, 125, 167, 168],
       [159, 170, 152, 184, 101, 158],
       [162, 142, 134, 169, 164, 176],
       [178, 146, 150, 150, 160, 191]])

### Найти диагональные элементы произведения матриц

In [113]:
first = np.random.random((6, 6))
second = np.random.random((6, 6))
np.diag(np.dot(first, second))

array([1.71942466, 0.76974954, 1.98191042, 1.65375099, 2.15491822,
       1.46686111])