# Антонов Павел - Третья лаба по NumPy

### Импортировать NumPy под именем np

In [2]:
import numpy as np

### Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [3]:
original_array = np.array([1,2,3,4,5])
result = np.zeros(17)
result[::4] = original_array
result

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

### Поменять 2 строки в матрице

In [4]:
result = np.arange(9).reshape(3,3)
result[[0,1]] = result[[1,0]]
result

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

### Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники

In [9]:
lines = np.random.randint(0,20,(10,3))
result = np.roll(lines.repeat(2,axis=1),-1,axis=1)
result = result.reshape(len(result)*3,2)
result = np.sort(result,axis=1)
result =result.view( dtype=[('point1',result.dtype),('point2',result.dtype)] )
np.unique(result)

array([( 0,  4), ( 0,  6), ( 1, 13), ( 1, 19), ( 2,  3), ( 2, 10),
       ( 2, 16), ( 2, 19), ( 3, 16), ( 3, 17), ( 3, 19), ( 4,  6),
       ( 5, 11), ( 5, 13), ( 5, 16), ( 5, 18), ( 7, 14), ( 7, 19),
       ( 8,  9), ( 8, 13), ( 8, 15), ( 9,  9), (10, 16), (11, 18),
       (13, 15), (13, 16), (13, 19), (14, 19), (16, 17)],
      dtype=[('point1', '<i4'), ('point2', '<i4')])

### Дан массив C; создать массив A, что np.bincount(A) == C

In [9]:
np.repeat(np.arange(4), np.bincount([0,1,1,3]))

array([0, 1, 1, 3])

### Посчитать среднее, используя плавающее окно

In [12]:
result = np.cumsum(np.array([2,8,9,1,7]))
result[3:] = result[3:] - result[:-3]
result[2:] / 3

array([6.33333333, 6.        , 5.66666667])

### Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))

In [15]:
from numpy.lib import stride_tricks

array = np.arange(5)
shape = (array.size - 2, 3)
strides = (array.itemsize, array.itemsize)
result = stride_tricks.as_strided(array, shape=shape, strides=strides)
array, result

(array([0, 1, 2, 3, 4]),
 array([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]]))

### Инвертировать булево значение, или поменять знак у числового массива без создания нового

In [13]:
result = np.random.randint(0,2,10)
print(result)
np.logical_not(result, out = result)
print(result)
np.negative(result, out=result)
print(result)

[0 1 1 0 0 1 1 0 1 0]
[1 0 0 1 1 0 0 1 0 1]
[-1  0  0 -1 -1  0  0 -1  0 -1]


### Посчитать ранг матрицы

In [16]:
result = np.random.uniform(0,1,(5,5))
print(result)
rank = np.linalg.matrix_rank(result)
print(rank)

[[0.455993   0.33564443 0.19266998 0.43863519 0.73831655]
 [0.93853642 0.93828234 0.1044358  0.08426935 0.69345157]
 [0.79448072 0.32811582 0.93461105 0.35124973 0.87442352]
 [0.73072164 0.63872675 0.39351442 0.2977077  0.35885501]
 [0.19829942 0.88609373 0.26739514 0.51515423 0.25653774]]
5


### Найти наиболее частое значение в массиве

In [19]:
np.bincount([0,1,1,3]).argmax()

1

### Извлечь все смежные 3x3 блоки из 10x10 матрицы

In [20]:
from numpy.lib import stride_tricks

array = np.random.randint(0,10,(10,10))
i = 1 + (array.shape[0] - 3)
j = 1 + (array.shape[1] - 3)
result = stride_tricks.as_strided(array, shape=(i, j, 3, 3), strides=array.strides + array.strides)
result

array([[[[2, 3, 2],
         [4, 2, 7],
         [4, 1, 1]],

        [[3, 2, 4],
         [2, 7, 6],
         [1, 1, 5]],

        [[2, 4, 0],
         [7, 6, 2],
         [1, 5, 3]],

        [[4, 0, 4],
         [6, 2, 3],
         [5, 3, 3]],

        [[0, 4, 5],
         [2, 3, 0],
         [3, 3, 8]],

        [[4, 5, 9],
         [3, 0, 8],
         [3, 8, 9]],

        [[5, 9, 8],
         [0, 8, 4],
         [8, 9, 2]],

        [[9, 8, 1],
         [8, 4, 8],
         [9, 2, 7]]],


       [[[4, 2, 7],
         [4, 1, 1],
         [4, 9, 4]],

        [[2, 7, 6],
         [1, 1, 5],
         [9, 4, 3]],

        [[7, 6, 2],
         [1, 5, 3],
         [4, 3, 4]],

        [[6, 2, 3],
         [5, 3, 3],
         [3, 4, 0]],

        [[2, 3, 0],
         [3, 3, 8],
         [4, 0, 5]],

        [[3, 0, 8],
         [3, 8, 9],
         [0, 5, 7]],

        [[0, 8, 4],
         [8, 9, 2],
         [5, 7, 3]],

        [[8, 4, 8],
         [9, 2, 7],
         [7, 3, 1]]],


    

### Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))

In [ ]:
#np.tensordot

### Дан массив 16x16, посчитать сумму по блокам 4x4

In [23]:
array = np.random.randint(0,10,(16,16))
result = np.add.reduceat(np.add.reduceat(array, np.arange(0, array.shape[0], 4), axis=0), np.arange(0, array.shape[1], 4), axis=1)
result

array([[62, 78, 77, 60],
       [54, 61, 52, 67],
       [68, 87, 75, 76],
       [67, 75, 62, 72]], dtype=int32)

### Найти n наибольших значений в массиве

In [24]:
np.sort(np.arange(10))[::-1][:3]

array([9, 8, 7])

### Построить прямое произведение массивов (все комбинации с каждым элементом)

In [41]:
result = [i * j for j in [1, 2, 3] for i in [4, 5, 6]]
result

[4, 5, 6, 8, 10, 12, 12, 15, 18]

### Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [31]:
array_a = np.random.randint(0,10,(8,3))
array_b = np.random.randint(0,10,(2,2))

for row in array_a:
    if all(item in array_b for item in row):
        print(row)

[2 2 7]


### Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])

In [34]:
array = np.random.randint(0,5,(10,3))
for row in array:
    flag = False
    for j in row:
        if row.tolist().count(j) > 1:
            flag = True
    if flag:
        print(row)

[4 4 3]
[3 0 3]
[1 0 0]
[4 4 2]
[0 2 0]
[3 4 4]
[0 3 3]


### Преобразовать вектор чисел в матрицу бинарных представлений

In [35]:
np.unpackbits(np.array([0, 2, 64, 101], dtype=np.uint8)[:, np.newaxis], axis=1)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 1, 0, 1]], dtype=uint8)

### Дан двумерный массив. Найти все различные строки

In [36]:
array = np.random.randint(0, 5, (5,5))
np.unique(array, axis=1)

array([[1, 1, 1, 2, 3],
       [0, 0, 3, 1, 2],
       [1, 4, 3, 0, 4],
       [1, 2, 3, 3, 1],
       [4, 1, 3, 0, 2]])

### Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

In [37]:
A = np.arange(10)
B = np.arange(10)

np.einsum('i->', A) # sum
np.einsum('i,i->i', A, B) # mul
np.einsum('i,j', A, B) # outer
np.einsum('i,i', A, B) # inner

285