# Антонов Павел - Первая лаба по NumPy

### Импортировать NumPy под именем np

In [53]:
import numpy as np

### Напечатать версию и конфигурацию

In [54]:
np.version.full_version

'1.18.5'

In [55]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 

### Создать вектор (одномерный массив) размера 10, заполненный нулями

In [56]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Создать вектор размера 10, заполненный единицами

In [57]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Создать вектор размера 10, заполненный числом 2.5

In [58]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

### Как получить документацию о функции numpy.add из командной строки?

In [59]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

### Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [60]:
tmp = np.zeros(10)
tmp[4] = 1
tmp

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### Создать вектор со значениями от 10 до 49

In [61]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Развернуть вектор (первый становится последним)

In [62]:
np.arange(1, 10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

### Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [63]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [64]:
np.array([1, 2, 0, 0, 4, 0]).nonzero()

(array([0, 1, 4], dtype=int64),)

### Создать массив 3x3x3 со случайными значениями

In [65]:
np.random.randint(3*3*3, size=(3, 3, 3))

array([[[10, 24, 14],
        [ 9, 14, 19],
        [20,  6, 22]],

       [[ 4, 17, 21],
        [ 4,  0, 22],
        [ 9, 20, 19]],

       [[13, 22,  8],
        [23, 22, 21],
        [20, 16,  3]]])

### Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [66]:
tmp = np.random.random((10,10))
print(tmp.min(), tmp.max(), sep=' ')

0.000546440586039143 0.9874452740906446


### Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [67]:
np.average(np.random.randint(30, size=(30,)))

15.8

### Создать матрицу с 0 внутри, и 1 на границах

In [68]:
tmp = np.zeros((3,3))
tmp[0][0] = 1
tmp[-1][-1] = 1
tmp

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

### Выяснить результат следующих выражений

In [69]:
0 * np.nan

nan

In [70]:
np.nan == np.nan

False

In [71]:
np.inf > np.nan

False

In [72]:
np.nan - np.nan

nan

### Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [73]:
np.diag(np.arange(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### Создать 8x8 матрицу и заполнить её в шахматном порядке

In [74]:
tmp = np.ones((8, 8))
tmp[1::2,::2] = 0
tmp[::2, 1::2] = 0
tmp

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

### Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [75]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

### Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [76]:
tmp = np.array([2, 1, 1, 2]).reshape((2, 2))
np.tile(tmp, (4, 4))

array([[2, 1, 2, 1, 2, 1, 2, 1],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [2, 1, 2, 1, 2, 1, 2, 1],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [2, 1, 2, 1, 2, 1, 2, 1],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [2, 1, 2, 1, 2, 1, 2, 1],
       [1, 2, 1, 2, 1, 2, 1, 2]])