# Антонов Павел - Вторая лаба по NumPy

### Импортировать NumPy под именем np

In [1]:
import numpy as np

### Перемножить матрицы 5x3 и 3x2

In [2]:
first_matrix = np.arange(15).reshape((5, 3))
second_matrix = np.arange(6).reshape((3, 2))
np.dot(first_matrix, second_matrix)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

### Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
vec = np.arange(10)
vec[(vec >= 3) & (vec <= 8)] *= -1
vec

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

### Создать 5x5 матрицу со значениями в строках от 0 до 4

In [4]:
vec = np.arange(5)
np.tile(vec, (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### Есть генератор, сделать с его помощью массив

In [5]:
iterable = (x*x for x in range(5))
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

### Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [6]:
np.linspace(0, 1, 12)[1:11]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

### Отсортировать вектор

In [7]:
vec = np.random.random((1,5))[0]
vec.sort()
vec

array([0.53576269, 0.59668531, 0.7483004 , 0.77757902, 0.80430067])

### Проверить, одинаковы ли 2 numpy массива

In [8]:
np.array_equal(np.arange(5), np.arange(5))

True

### Сделать массив неизменяемым

In [9]:
vec = np.arange(5)
vec.flags.writeable = False

### Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [10]:
vec = np.random.random((10, 2))
x, y = vec[:,0], vec[:,1]
np.array([np.sqrt(x**2 + y**2), np.arctan2(y, x)])

array([[0.46098064, 0.55932929, 0.74525894, 0.55229304, 0.95459847,
        0.69005686, 0.25622856, 1.15942887, 0.77143127, 0.59280041],
       [0.70004373, 0.94927164, 1.13588405, 0.6024556 , 0.85005717,
        0.8210135 , 0.49123196, 0.66530432, 1.51244361, 0.37829585]])

### Заменить максимальный элемент на ноль

In [11]:
vec = np.arange(5)
vec[vec.argmax()] = 0
vec

array([0, 1, 2, 3, 0])

### Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [12]:
x, y = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
result = np.column_stack((x.ravel(), y.ravel()))
result.reshape(1, 50).reshape(5, 5, 2)

array([[[0.  , 0.  ],
        [0.25, 0.  ],
        [0.5 , 0.  ],
        [0.75, 0.  ],
        [1.  , 0.  ]],

       [[0.  , 0.25],
        [0.25, 0.25],
        [0.5 , 0.25],
        [0.75, 0.25],
        [1.  , 0.25]],

       [[0.  , 0.5 ],
        [0.25, 0.5 ],
        [0.5 , 0.5 ],
        [0.75, 0.5 ],
        [1.  , 0.5 ]],

       [[0.  , 0.75],
        [0.25, 0.75],
        [0.5 , 0.75],
        [0.75, 0.75],
        [1.  , 0.75]],

       [[0.  , 1.  ],
        [0.25, 1.  ],
        [0.5 , 1.  ],
        [0.75, 1.  ],
        [1.  , 1.  ]]])

### Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [13]:
x, y = np.meshgrid(np.linspace(2, 3, 5), np.linspace(0, 1, 5), indexing="xy")
result = 1 / (x - y)
result

array([[0.5       , 0.44444444, 0.4       , 0.36363636, 0.33333333],
       [0.57142857, 0.5       , 0.44444444, 0.4       , 0.36363636],
       [0.66666667, 0.57142857, 0.5       , 0.44444444, 0.4       ],
       [0.8       , 0.66666667, 0.57142857, 0.5       , 0.44444444],
       [1.        , 0.8       , 0.66666667, 0.57142857, 0.5       ]])

### Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [14]:
np_ints = [np.uint, np.uint0, np.uint16, np.uint32, np.uint64, np.uint8, np.uintc, np.uintp, np.int, np.int0, np.int16, np.int32, np.int64, np.int8, np.intc, np.integer, np.intp]
np_floats = [np.float, np.float16, np.float32, np.float64]

for type_int in np_ints:
    type_info = np.iinfo(type_int)
    print("Название", type_int, "MIN:", type_info.min, "MAX:", type_info.max)

for type_float in np_floats:
    type_info = np.finfo(type_float)
    print("Название", type_float, "MIN:", type_info.min, "MAX:", type_info.eps)

Название <class 'numpy.uint32'> MIN: 0 MAX: 4294967295
Название <class 'numpy.uint64'> MIN: 0 MAX: 18446744073709551615
Название <class 'numpy.uint16'> MIN: 0 MAX: 65535
Название <class 'numpy.uint32'> MIN: 0 MAX: 4294967295
Название <class 'numpy.uint64'> MIN: 0 MAX: 18446744073709551615
Название <class 'numpy.uint8'> MIN: 0 MAX: 255
Название <class 'numpy.uintc'> MIN: 0 MAX: 4294967295
Название <class 'numpy.uint64'> MIN: 0 MAX: 18446744073709551615
Название <class 'int'> MIN: -2147483648 MAX: 2147483647
Название <class 'numpy.int64'> MIN: -9223372036854775808 MAX: 9223372036854775807
Название <class 'numpy.int16'> MIN: -32768 MAX: 32767
Название <class 'numpy.int32'> MIN: -2147483648 MAX: 2147483647
Название <class 'numpy.int64'> MIN: -9223372036854775808 MAX: 9223372036854775807
Название <class 'numpy.int8'> MIN: -128 MAX: 127
Название <class 'numpy.intc'> MIN: -2147483648 MAX: 2147483647
Название <class 'numpy.integer'> MIN: -2147483648 MAX: 2147483647
Название <class 'numpy.int64

### Напечатать все значения в массиве

In [15]:
vec = np.arange(5)
for tmp in vec:
    print(tmp)

0
1
2
3
4


### Найти ближайшее к заданному значению число в заданном массиве

In [16]:
tmp = 5.6
vec = np.arange(10)
vec[(np.abs(vec - tmp)).argmin()]

6

### Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)

In [31]:
result = np.zeros(10, [('coordinate', [('x', np.float), ('y', np.float)]), ('color', [('r', np.uint8), ('g', np.uint8), ('b', np.uint8)])])
result

array([((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0))],
      dtype=[('coordinate', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', 'u1'), ('g', 'u1'), ('b', 'u1')])])

### Дан массив (100,2) координат, найти расстояние от каждой точки до каждой

In [18]:
coordinates = np.random.random((100, 2))
result = np.zeros((100, 100))
for i in range(100):
    for j in range(100):
        result[i][j] = np.linalg.norm(np.abs(coordinates[i] - coordinates[j]))
result

array([[0.        , 0.35640328, 0.47051102, ..., 0.26476723, 0.88134996,
        0.78966017],
       [0.35640328, 0.        , 0.28876637, ..., 0.10875534, 0.61048054,
        0.53062076],
       [0.47051102, 0.28876637, 0.        , ..., 0.3566009 , 0.84592544,
        0.32230879],
       ...,
       [0.26476723, 0.10875534, 0.3566009 , ..., 0.        , 0.64201335,
        0.62884176],
       [0.88134996, 0.61048054, 0.84592544, ..., 0.64201335, 0.        ,
        0.91148772],
       [0.78966017, 0.53062076, 0.32230879, ..., 0.62884176, 0.91148772,
        0.        ]])

### Преобразовать массив из float в int

In [19]:
np.random.random(10).astype(np.int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Дан файл: Как прочитать его?

In [34]:
with open('./test.txt', 'w') as out:
    out.write("1 1 1 1 1  5")

np.genfromtxt('./test.txt', delimiter=' ')

array([ 1.,  1.,  1.,  1.,  1., nan,  5.])

### Каков эквивалент функции enumerate для numpy массивов?

In [36]:
list(np.ndenumerate(np.zeros(5)))

[((0,), 0.0), ((1,), 0.0), ((2,), 0.0), ((3,), 0.0), ((4,), 0.0)]

### Сформировать 2D массив с распределением Гаусса

In [22]:
np.random.normal(size=(5, 5))

array([[ 0.85845947,  0.47214939, -0.76999715,  0.741486  , -1.05711751],
       [ 0.11435129, -0.03998564, -0.64501975, -0.25239448,  1.16912741],
       [-0.71322811, -2.2712283 ,  0.45698071,  1.5749901 , -0.27126837],
       [ 0.08754235, -0.25815814,  0.8671849 ,  1.38545942,  1.14590753],
       [ 0.56399059, -0.38198709,  0.92780232,  1.04344073, -2.21604227]])

### Случайно расположить p элементов в 2D массив

In [23]:
result = np.zeros((5,5))
np.put(result, np.random.choice(range(25), 10, replace=False), -1)
result

array([[-1.,  0., -1., -1.,  0.],
       [ 0., -1.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0., -1.],
       [-1., -1.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0., -1.]])

### Отнять среднее из каждой строки в матрице

In [24]:
result = np.arange(49).reshape(7, 7)
result = result - result.mean(axis=1)
result

array([[ -3.,  -9., -15., -21., -27., -33., -39.],
       [  4.,  -2.,  -8., -14., -20., -26., -32.],
       [ 11.,   5.,  -1.,  -7., -13., -19., -25.],
       [ 18.,  12.,   6.,   0.,  -6., -12., -18.],
       [ 25.,  19.,  13.,   7.,   1.,  -5., -11.],
       [ 32.,  26.,  20.,  14.,   8.,   2.,  -4.],
       [ 39.,  33.,  27.,  21.,  15.,   9.,   3.]])

### Отсортировать матрицу по n-ому столбцу

In [25]:
result = np.arange(49).reshape(7, 7)[::-1]
result[result[:,2].argsort()]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

### Определить, есть ли в 2D массиве нулевые столбцы

In [40]:
result = np.array([[0, 0, 2], [1, 0, 3]])
np.all((result == 0), axis=0)

array([False,  True, False])

### Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [27]:
a = np.ones(10)
b = np.arange(10)
for i in b:
    a[i] += 1
a
# или bincount

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

### Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [54]:
vector = np.random.randint(0, 256, (100, 100, 3)).astype(np.ubyte)
result = vector.reshape((10000, 3))
len(np.unique(result, axis=0))

9996

### Дан четырехмерный массив, посчитать сумму по последним двум осям

In [55]:
array = np.random.randint(0,10, (6,6,6,6))
result = array.reshape(array.shape[:-2] + (-1,)).sum(axis=-1)
result

(6, 6, -1)


array([[149, 166, 147, 142, 163, 174],
       [130, 146, 140, 147, 150, 184],
       [188, 154, 170, 160, 149, 185],
       [144, 172, 145, 154, 164, 169],
       [173, 188, 151, 169, 158, 177],
       [172, 181, 173, 157, 155, 153]])

### Найти диагональные элементы произведения матриц

In [30]:
first = np.random.random((6, 6))
second = np.random.random((6, 6))
np.diag(np.dot(first, second))

array([1.3189164 , 0.94249794, 1.12809457, 1.99416144, 3.15800941,
       1.51656322])